define("templates_event/wday", function() {}), define("templates_event/wday/dungeon/List", [], function() {
    return function(a) {
        function print() {
            __p += __j.call(arguments, "")
        }
        a || (a = {});
        var b, __p = "",
            __e = _.escape,
            __j = Array.prototype.join;
        with(a) __p += '<div class="c-layer-bg w-full h-full" data-app-layer-bg></div>\n<div class="c-layer-content-1 scene-wday-dungeon-list">\n    <div class="c-freescroll-wrap">\n        <div class="c-freescroll" data-ui-freescroll data-app-dungeon-list-scroll>\n            <div data-ui-freescroll-content>\n                <ul class="mb-b4">\n                    ', _.each(dungeonModels, function(e) {
            __p += '\n                        <li class="mb-b2">\n                            <div class="c-btn is-thick-long mlr-a" data-dungeon-id="' + __e(e.get("id")) + '" data-mbgaui-anchors data-app-sound="choose" data-app-flag-unlock data-app-dungeon-info>\n                                <div class="c-btn__inner">\n                                    <div class="mb-b">' + __e(e.get("name")) + '</div>\n                                    <div class="c-text-mat s-text-layout">\n                                        <div class="c-text-mat__inner">\n                                            <dl class="c-label box-cb">\n                                                <dt class="c-label__img"><div class="p-text-total-stamina img-rep">総消費スタミナ</div></dt>\n                                                <dd class="c-label__text s-text-layout__num">' + __e(e.get("total_stamina")) + "</dd>\n                                            </dl>\n                                        </div>\n                                    </div>\n                                </div>\n\n                                ", e.get("is_master") ? __p += '\n                                    <div class="p-text-master img-rep s-badge">Master</div>\n                                ' : e.get("is_clear") && (__p += '\n                                    <div class="p-text-clear img-rep s-badge">clear</div>\n                                '), __p += "\n                            </div>\n                         </li>\n                     "
        }), __p += '\n                </ul>\n                <div class="c-btn is-nav-small s-btn-intro" data-mbgaui-anchors data-app-sound="choose" data-app-btn-intro>\n                    <span class="c-btn__inner fs-xs">Daily Dungeon Rules</span>\n                </div>\n            </div>\n            <div class="c-freescroll__scrollbar" data-ui-scrollbar><div class="c-freescroll__scrollbar-inner" data-ui-scrollbar-face></div></div>\n        </div>\n    </div>\n</div>\n\n<div class="c-layer-content-11 scene-wday-dungeon-list" data-app-dungeon-list>\n    <h1 class="c-ttl-scene">\n        <span class="c-ttl-scene__inner">\n            ' + __e(worldModel.get("name")) + '\n        </span>\n    </h1>\n    <a class="c-btn-back img-rep" data-app-btn-back data-mbgaui-anchors data-app-sound="choose">戻る</a>\n\n</div>\n<div data-app-dungeon-detail></div>\n';
        return __p
    }
}), define("templates_event/wday/dungeon_list/DungeonDetail", [], function() {
    return function(a) {
        function print() {
            __p += __j.call(arguments, "")
        }
        a || (a = {});
        var b, __p = "",
            __e = _.escape,
            __j = Array.prototype.join;
        with(a) {
            __p += ' <div class="c-layer-content-1 dungeon-detail-scroll wday">\n', dungeonModel.hasCaptures() ? __p += '\n    <ul class="mod-tab-content-modal tab-type2" data-app-tab-small>\n        <li data-ui-group="tab" data-mbgaui-anchors="{ preventDefault: true }" data-app-sound="choose" class="is-current"><span class="inner">Rewards</span></li>\n        <li data-ui-group="tab" data-mbgaui-anchors="{ preventDefault: true }" data-app-sound="choose"><span class="inner">BOSS</span></li>\n    </ul>\n    <div class="mod-paper-container">\n' : __p += '\n    <div class="mod-paper-container only-content-adjust">\n        <h1 class="hdr-content-sub"><span class="inner">Rewards</span></h1>\n', __p += '\n        <div class="mod-freescroll-wrap mod-basic" data-ui-freescroll="detail">\n            <div class="freescroll-mask">\n                <div data-ui-freescroll-content>\n                    <div data-ui-group="pane" class="is-current">\n                        <section>\n                            <h1 class="c-ttl-section mb-b">Item Highlights</h1>\n                            <ul>\n                            ', _.each(eventWdayDungenModel.get("attention_items"), function(e) {
                __p += '\n                                <li class="box-c mb-b">\n                                    <div class="mr-b"><img src="' + __e(pUrl(e.image_path)) + '" width="35" height="35"></div>\n                                     <p class="s-ww-prize-name">' + __e(e.name), e.num && (FF.env.isWWRegion ? __p += "&nbsp;x" : __p += "&times;", __p += __e(e.num)), __p += "</p>\n                                </li>\n                            "
            }), __p += '\n                            </ul>\n                            <div class="mod-bar-content mb-b">\n                                <p class="mod-bar-content-inner">\n                                    Tips & Tactics<br>\n                                    ' + __e(eventWdayDungenModel.get("description")) + "\n                                </p>\n                            </div>\n                        </section>\n\n                        ";
            var c = FF.CONST.SERVER.DUNGEON.PRIZE_TYPE_OF;
            __p += "\n                        ", _.each(dungeonModel.getSortedDungeonPrizes(), function(e) {
                __p += "\n                            ";
                var t = e.type;
                __p += "\n                            ";
                var n = e.items;
                __p += '\n                            <section>\n                                <h1 class="c-ttl-section mb-b">\n                                    ', t == c.FIRST_CLEAR && (__p += "First Time Reward"), __p += "\n                                    ", t == c.CLEAR && (__p += "Completion Reward"), __p += "\n                                    ", t == c.FIRST_MASTER && (__p += "Mastery Reward"), __p += "\n                                </h1>\n                                <ul>\n                                ";
                var r = dungeonModel.isAcquisitionByPrizeType(t);
                __p += "\n                                ", _.each(n, function(e) {
                    __p += '\n                                    <li class="box-c mb-b">\n                                        <div class="mr-b', r && (__p += " c-acquisition"), __p += '"><img src="' + __e(pUrl(e.image_path)) + '" width="35" height="35"></div>\n                                         <p class="s-ww-prize-name">' + __e(e.name), FF.env.isWWRegion ? __p += "&nbsp;x" : __p += "&times;", __p += __e(e.num) + "</p>\n                                    </li>\n                                "
                }), __p += "\n                                </ul>\n                            </section>\n                        "
            }), __p += "\n                    </div>\n                    ", dungeonModel.hasCaptures() && (__p += '\n                        <div data-ui-group="pane">\n                        ', _.each(dungeonModel.getCaptures(), function(e) {
                __p += "\n                            ";
                var t = e.tip_battle;
                __p += "\n                            ";
                var n = e.sp_scores;
                __p += '\n                            <section class="mb-b2 mod-text-style">\n                                <h1 class="hdr-content-sub04 mb-b2">' + __e(t.title) + '</h1>\n                                <div class="ta-c mb-b2">\n                                    <img src="' + __e(pUrl(e.image_path)) + '" width="250" height="auto">\n                                </div>\n                                <p class="mb-b3 pl-b pr-b">' + ((b = util.nl2br(t.message)) == null ? "" : b) + "</p>\n                                ", n && n.length > 0 && (__p += '\n                                    <div class="bg-detail-point box-cc po-r ml-a mr-a">\n                                        <h1 class="img-text-special-score img-rep">special score</h1>\n                                        <div>\n                                            ', _.each(n, function(e) {
                    __p += '\n                                                <p class="fc-light">' + __e(e.title) + "</p>\n                                            "
                }), __p += "\n                                        </div>\n                                    </div>\n                                "), __p += "\n                            </section>\n                        "
            }), __p += "\n                        </div>\n                    "), __p += '\n                </div>\n            </div>\n            <div class="scrollbar" data-ui-scrollbar="detail"><div class="inner" data-ui-scrollbar-face></div></div>\n        </div>\n    </div>\n</div>\n\n<div class="c-layer-content-11 dungeon-detail wday">\n    <h1 class="c-ttl-scene">\n        <span class="c-ttl-scene__inner">\n            ' + __e(worldModel.get("name")) + '\n        </span>\n    </h1>\n    <div class="dungeon-detail-plate">\n        <ul class="rank-badge add-rank-badge' + __e(dungeonModel.get("rank")) + " ", dungeonModel.get("is_master") ? __p += "add-master" : dungeonModel.get("is_clear") && (__p += "add-clear"), __p += '">\n            <!-- rank badge container -->\n            <li></li>\n            <li></li>\n            <li></li>\n        </ul>\n    </div>\n    <div id=\'dungeon-detail-back\' class="c-btn-back" data-app-btn-back data-mbgaui-anchors data-app-sound="choose"></div>\n\n    <div class="c-btn-layout">\n        <div class="bg-total-stamina box-cc">\n            <div class="box-cc">\n                <div class="p-text-total-stamina img-rep">総消費スタミナ</div>\n                <div class="ta-c fc-light fs-s">' + __e(dungeonModel.get("total_stamina")) + '</div>\n            </div>\n        </div>\n        <a class="c-btn is-main-lead c-btn-layout__center" data-mbgaui-anchors data-app-sound="decide" data-app-btn-go><span class="c-btn__inner">GO!</span></a>\n    </div>\n</div>'
        }
        return __p
    }
}), define("templates_event/wday/dungeon_list/DungeonList", [], function() {
    return function(a) {
        function print() {
            __p += __j.call(arguments, "")
        }
        a || (a = {});
        var b, __p = "",
            __e = _.escape,
            __j = Array.prototype.join;
        with(a) __p += '<div class="c-layer-bg w-full h-full" data-app-layer-bg></div>\n<div class="c-layer-content-1 dungeon-list-layout-scroll mod-freescroll-wrap mod-basic" data-ui-freescroll data-app-dungeon-list-scroll>\n    <div data-ui-freescroll-content>\n        <ul class="list-decoration layout-wday">\n            ', _.each(dungeonModels, function(e) {
            __p += '\n                <li data-dungeon-id="' + __e(e.get("id")) + '" data-mbgaui-anchors data-app-sound="choose" data-app-flag-unlock>\n                    <div class="inner box-cb flex1">\n                        <div>' + __e(e.get("name")) + "</div>\n                    </div>\n                    ", e.get("is_master") ? __p += '\n                        <div class="img-text-master img-rep">Master</div>\n                    ' : e.get("is_clear") && (__p += '\n                        <div class="img-text-clear img-rep">clear</div>\n                    '), __p += "\n                 </li>\n             "
        }), __p += '\n        </ul>\n        <div class="btn-wide" data-mbgaui-anchors data-app-sound="choose" data-app-btn-intro>\n            <span class="inner">Daily Dungeon Rules</span>\n        </div>\n    </div>\n    <div class="c-freescroll__scrollbar" data-ui-scrollbar><div class="c-freescroll__scrollbar-inner" data-ui-scrollbar-face></div></div>\n</div>\n\n<div class="c-layer-content-11 dungeon-list-layout wday" data-app-dungeon-list>\n    <h1 class="c-ttl-scene">\n        <span class="c-ttl-scene__inner">\n            ' + __e(worldModel.get("name")) + '\n        </span>\n    </h1>\n    <a class="c-btn-back" data-app-btn-back data-mbgaui-anchors data-app-sound="choose"></a>\n\n</div>\n<div data-app-dungeon-detail></div>\n';
        return __p
    }
}), define("templates_event/wday/ModalDungeonInfo", [], function() {
    return function(a) {
        function print() {
            __p += __j.call(arguments, "")
        }
        a || (a = {});
        var b, __p = "",
            __e = _.escape,
            __j = Array.prototype.join;
        with(a) {
            var c = FF.CONST.SERVER.DUNGEON.PRIZE_TYPE_OF;
            __p += '\n\n<div class="scene-modal-dungeon-detail c-modal-window">\n    <div class="c-modal-window__inner">\n        <h1 class="c-ttl-scene">\n            ', helper.isSeriesIconDefined(seriesId) && (__p += '\n                <span class="c-ttl-scene__img p-icon-' + __e(seriesId) + ' img-rep">' + __e(seriesId) + "</span>\n            "), __p += '\n            <span class="c-ttl-scene__inner ls-xxs fs-l lh-s">' + __e(dungeonModel.get("name")) + '</span>\n        </h1>\n\n        <div class="c-dungeon-detail-plate mlr-a box-cc">\n            <dl class="c-label">\n                <dt class="c-label__img"><div class="p-text-total-stamina img-rep">総消費スタミナ</div></dt>\n                <dd class="c-label__text">' + __e(dungeonModel.get("total_stamina")) + '</dd>\n            </dl>\n        </div>\n\n            <div class="c-paper-container mb-b2 s-only-content">\n                <div class="c-paper-container__inner">\n                <h1 class="c-ttl-category"><span class="c-ttl-category__inner">Rewards</span></h1>\n                <div class="c-freescroll" data-ui-freescroll="dungeon-info">\n                    <div data-ui-freescroll-content>\n                        <div data-ui-group="pane" data-ui-tab-name="prize">\n\n                            <section class="c-paper-container__content">\n                                <h1 class="c-ttl-section mb-b">Item Highlights</h1>\n                                <ul>\n                                ', _.each(eventWdayDungenModel.get("attention_items"), function(e) {
                __p += '\n                                    <li class="box-c mb-b">\n                                        <div class="mr-b"><img src="' + __e(pUrl(e.image_path)) + '" width="35" height="35"></div>\n                                         <p class="s-ww-prize-name">' + __e(e.name), e.num && (FF.env.isWWRegion ? __p += "&nbsp;x" : __p += "&times;", __p += __e(e.num)), __p += "</p>\n                                    </li>\n                                "
            }), __p += '\n                                </ul>\n                                <div class="c-bar-content mb-b">\n                                    <p class="c-bar-content__inner">\n                                        Strategy Tips<br>\n                                        ' + __e(eventWdayDungenModel.get("description")) + "\n                                    </p>\n                                </div>\n                            </section>\n                            ", _.each(dungeonModel.getSortedDungeonPrizes(), function(e) {
                __p += "\n                                ";
                var t = e.type;
                __p += "\n                                ";
                var n = e.items;
                __p += '\n                                <section>\n                                    <h1 class="c-ttl-section mb-b">\n                                        <span class="c-ttl-section__inner">\n                                            ', t == c.CLEAR && (__p += "Completion Reward"), __p += "\n                                            ", t == c.FIRST_CLEAR && (__p += "First Time Reward"), __p += "\n                                            ", t == c.FIRST_MASTER && (__p += "Mastery Reward"), __p += '\n                                        </span>\n                                    </h1>\n                                    <ul class="ml-b2 mr-b2">\n                                        ';
                var r = dungeonModel.isAcquisitionByPrizeType(t);
                __p += "\n                                        ", _.each(n, function(e) {
                    __p += '\n                                            <li class="box-c mb-b">\n                                                <div class="mr-b', r && (__p += " c-acquisition"), __p += '"><img src="' + __e(pUrl(e.image_path)) + '" width="35" height="35"></div>\n                                                <p class="s-ww-prize-name">' + __e(e.name), FF.env.isWWRegion ? __p += "&nbsp;x" : __p += "&times;", __p += __e(e.num) + "</p>\n                                            </li>\n                                        "
                }), __p += "\n                                    </ul>\n                                </section>\n                            "
            }), __p += '\n                        </div>\n                    </div>\n                    <div class="c-freescroll__scrollbar" data-ui-scrollbar="detail"><div class="c-freescroll__scrollbar-inner" data-ui-scrollbar-face></div></div>\n                </div>\n            </div>\n        </div>\n        <div class="c-btn-layout">\n            ', enableChallengeButton ? __p += '\n                <div class="c-btn is-sub-lead c-btn-layout__left" data-mbgaui-anchors data-app-sound="choose" data-app-modal-close data-app-enable-back-key="true">\n                    <span class="c-btn__inner">Close</span>\n                </div>\n                <div class="c-btn is-main-lead c-btn-layout__right" data-mbgaui-anchors data-app-modal-challenge data-app-sound="decide">\n                    <span class="c-btn__inner">Enter Dungeon</span>\n                </div>\n            ' : __p += '\n                <div class="c-btn is-sub-lead c-btn-layout__center" data-mbgaui-anchors data-app-sound="choose" data-app-modal-close data-app-enable-back-key="true">\n                    <span class="c-btn__inner">Close</span>\n                </div>\n            ', __p += "\n        </div>\n    </div>\n</div>\n"
        }
        return __p
    }
});